dropout: 0.1

name: ncsnpp
scale_by_sigma: True
ema_rate: 0.9999
normalization: GroupNorm
nonlinearity: swish
nf: 128
ch_mult: [1, 2, 2, 2]
num_res_blocks: 8
attn_resolutions: [16,]
resamp_with_conv: True
conditional: True
fir: False
fir_kernel: [1, 3, 3, 1]
skip_rescale: True
resblock_type: biggan
progressive: none
progressive_input: residual
progressive_combine: sum
attention_type: ddpm
init_scale: 0.
embedding_type: fourier
fourier_scale: 16
conv_size: 3
