name: ncsnpp
channels: 3
image_size: 5
image_width: 5
num_classes: 1
cond_drop_prob: 0.3
conditional: true
init_scale: 0.
ema_rate: 0.9999
nf: 512
ch_mult: [1, 2, 4]
num_res_blocks: 4
attn_resolutions: [5]
resamp_with_conv: true
embedding_type: fourier
progressive: output_skip
progressive_input: residual
progressive_combine: sum
progressive_output_skip: true
fourier_scale: 32
resblock_type: biggan
skip_rescale: true
nonlinearity: swish
fir: false
fir_kernel: [1, 3, 3, 1]
dropout: 0.5
scale_by_sigma: false 