name: ncsnpp
channels: 3
image_size: 9
image_width: 9
num_classes: 1
cond_drop_prob: 0.5
conditional: true
init_scale: 0.
ema_rate: 0.999
nf: 64
ch_mult: [1, 2, 2]
num_res_blocks: 2
attn_resolutions: [9]
resamp_with_conv: true
embedding_type: fourier
progressive: none
progressive_input: none
progressive_combine: sum
progressive_output_skip: false
fourier_scale: 16
resblock_type: ddpm
skip_rescale: true
nonlinearity: swish
fir: false
fir_kernel: [1, 3, 3, 1]
dropout: 0.2
scale_by_sigma: false 