defaults:
  - _self_
  - model: ncsnpp
  - data: gto_halo_optimal
  - override hydra/launcher: submitit_slurm

ngpus: 1
dataroot: datasets

training:
  batch_size: 1792  # Optimized for 80GB GPU (2x scaling from 40GB baseline)
  n_iters: 40000
  snapshot_freq: 500
  log_freq: 1
  eval_freq: 200
  snapshot_freq_for_preemption: 10000
  snapshot_sampling: True
  likelihood_weighting: False
  reduce_mean: False
  drop_label: 0.2

eval:
  batch_size: 1792  # Optimized for 80GB GPU (2x scaling from 40GB baseline)

sde: 
  name: vesde
  sigma_min: 0.005
  sigma_max: 10
  num_scales: 2000

sampling:
  n_steps_each: 1
  noise_removal: True
  probability_flow: False
  snr: 0.005
  guidance_scale: 1.5
  method: pc
  predictor: euler_maruyama
  corrector: none
  denoiser: none

optim:
  weight_decay: 0
  optimizer: Adam
  lr: 0.000320  # Scaled by √2 for batch size increase (896->1792)
  beta1: 0.9
  beta2: 0.999
  eps: 1e-8
  warmup: 8000
  grad_clip: 1.0

hydra:
  run:
    dir: ../Training Runs/${now:%Y.%m.%d_%H%M%S}
  sweep:
    dir: ../Training Runs/${now:%Y.%m.%d_%H%M%S}
    subdir: ${hydra.job.num}
  # launcher:
  #   max_num_timeout: null
  #   timeout_min: null
  #   partition: null
  #   account: null
  #   mem_gb: null
  #   cpus_per_task: null
  #   gpus_per_node: ${ngpus}
  #   constraint: null

checkpoint_path: "Training Runs/2025.08.19_161122/checkpoints/checkpoint_8.pth"
